---
- name: install git os pkgs...
  become: '{{ git_privilege_escalation }}'
  become_user: root
  package:
    name: '{{ git_os_pkgs }}'
    state: present

- name: install git-lfs os pkgs...
  when: git_lfs_enable
  become: '{{ git_privilege_escalation }}'
  become_user: root
  package:
    name: '{{ git_lfs_os_pkgs }}'
    state: present
